version: '3.8'

services:
  iptv-helper:
    build: .
    container_name: iptv-helper
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./output:/app/output
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
    command: >
      sh -c "python src/main.py sync-channels &&
             python src/main.py run"
    
    # 可选: 使用 PostgreSQL 数据库
    # depends_on:
    #   - postgres
    # environment:
    #   - DATABASE__URL=postgresql://iptv:password@postgres:5432/iptv_helper

  # 可选: PostgreSQL 数据库
  # postgres:
  #   image: postgres:15
  #   container_name: iptv-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: iptv_helper
  #     POSTGRES_USER: iptv
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # 可选: 使用 cron 定时任务
  iptv-scheduler:
    build: .
    container_name: iptv-scheduler
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./output:/app/output
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
    command: >
      sh -c "echo '0 */6 * * * cd /app && python src/main.py run' | crontab - && crond -f"

  # 可选: 静态文件服务器
  web-server:
    image: nginx:alpine
    container_name: iptv-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html:ro
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro

# 可选: 数据卷
# volumes:
#   postgres_data: